spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        min-idle: 0
        max-idle: 20
  data:
    solr:
      host: http://localhost:8983/solr