server:
  port: 8080
# solr配置及数据库
spring:
  datasource:
    username: root
    password: MySQL@2019
    url: jdbc:mysql://47.94.36.91:3306/meituan?useUnicode=true&characterEncoding=UTF8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/mapper/*.xml
#  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org.lanqiao:
      mapper : debug

